### PR TITLE
Introduce `Driver` API

### PR DESCRIPTION
**Pull request by hannobraun**
This is a first step towards reducing the duplication between drivers, as laid out in #31. I'm already working on the next few steps, but those turned out to be a bit more involved than I had assumed. I figure it's better to get this merged piecemeal, to keep each pull request digestible.

### CODE REVIEW

**Comment by hannobraun** [comment]
Oops, forgot to update the test stand. I'm marking this as a draft until I had a chance to update it.

**Comment by hannobraun** [comment]
I've updated the test stand. This is ready for review now.

The test stand now fails for me. This is not because of any changes made here, as I have the same problems on master. It's probably related to my setup (I have to pack away the test stand between uses, for lack of space, and something probably moved).

**Comment by hannobraun** [comment]
Since this was still un-reviewed, I've taken the opportunity to make some more modifications to the commits. But now I'm done, promise!

**Review by jessebraham — APPROVED** [review]
Sorry for the delay in getting to this! I've been having a busy week :)

Overall this looks great, thank you (yet again) for your continued efforts! I initially had a few suggestions (mainly splitting out the traits into another module) but it looks like you have covered them with the last batch of commits so that's awesome.

**Comment by hannobraun** [comment]
No problem, and thanks for the review!

**Pull request merged**
