### PR TITLE
Add test stand

### PR DESCRIPTION
**Pull request by hannobraun**
Add a test stand with a simple test suite for the STSPIN220. The DRV8825 is not being tested yet, mainly because I needed to start somewhere and don't have the hardware yet. Eventually, I'd like to have a hardware setup that includes all supported driver boards and tests each of them. This would be a bit of work, however, and I think this is a nice first step, and easy enough to adapt to other drivers.

The test stand design has some problems, as noted in the README. I intend to address those in future iterations, but help would be welcome, of course.

I've submitted this to get some feedback, but this is not quite ready for merging yet:
- [x] Includes the commit from #25. I'd like to get that merged first.
- [x] ~~Doesn't test `SetStepMode` yet. I'll look into that next week.~~

### CODE REVIEW

**Comment by jessebraham** [comment]
I think this is a good start, it gives us a solid base to build upon. As stated it's easy enough to adapt this to other drivers for the time being; once there are more we may consider making things a bit more generic if possible.

What are your thoughts on testing in various step modes? I don't think it needs to be exhaustive but it probably wouldn't hurt to verify that eg.) stepping in 1/2 step mode requires 400 steps per rotation. Unfortunately due to the relatively low resolution of the encoder I'm not sure how effective this will be, as the margin of error is likely several steps, so I'm just curious what you think about this.

The 3D printed portion is probably my only concern at this point, mostly due to its size. I think it's a cool idea trying to match the breadboard form factor but it just seems like a bit of a waste of material and print time in its current state. I will play around with this a bit and see if I can come up with something a bit more compact. If I do manage to come up with anything I will share of course. If you have any further input on this as well please let me know.

I do plan on building a test stand of my own as well (just sourcing the last couple parts currently) so I will be testing the hardware I own as well once that is done.

**Comment by hannobraun** [comment]
Rebased on master.


@jessebraham 
> I think this is a good start, it gives us a solid base to build upon. As stated it's easy enough to adapt this to other drivers for the time being; once there are more we may consider making things a bit more generic if possible.

Thank you for the feedback!


> What are your thoughts on testing in various step modes? I don't think it needs to be exhaustive but it probably wouldn't hurt to verify that eg.) stepping in 1/2 step mode requires 400 steps per rotation. Unfortunately due to the relatively low resolution of the encoder I'm not sure how effective this will be, as the margin of error is likely several steps, so I'm just curious what you think about this.

I think that the main thing we need to test here is that our driver code doesn't mess up the step mode configuration. So what I'm planning is to run a revolution in every step mode configuration supported by a given driver, and check that the encoder reported 20 counts. That is not good enough to catch missed steps, but if it reported 10 or 40 counts, you'll notice.

Eventually, we should look into a higher-resolution encoder that doesn't cost a fortune, to catch lost steps due to timing problems and stuff like that. But one thing at a time.


> The 3D printed portion is probably my only concern at this point, mostly due to its size. I think it's a cool idea trying to match the breadboard form factor but it just seems like a bit of a waste of material and print time in its current state. I will play around with this a bit and see if I can come up with something a bit more compact. If I do manage to come up with anything I will share of course. If you have any further input on this as well please let me know.

Fully agreed. I don't have any input at this time, beyond the items I added to the README.

As stated above, I'll take another look at this at some point. I want a magic test stand that supports all drivers without the need to make manual adjustments. We'll probably need a custom PCB for that, so things will change anyway.

> I do plan on building a test stand of my own, so I will be testing the hardware I own as well once that is done.

:+1: 

Probably the best approach for now would be to add another test file and tell people to add `--test drv8825` or whatever, to test what they have available. The core testing functions only depend on the traits and can be re-used, so adding more test modules should just require the setup code plus a bit of boilerplate for the tests.

**Comment by jessebraham** [comment]
(Just an update, no need to reply)

I have ordered the magnetic encoder and it should (hopefully) arrive in a few days. I will be ordering an LPC845-BRK‎ this week as well which should arrive by the time the encoder does.

I had a NEMA11 stepper motor laying around for some reason, so just to avoid spending money I'm going to try to make the test stand work with both NEMA11/NEMA14. I was able to rotate the additional mounting holes 45° from the existing set to allow for either motor size in my model.

I have nearly completed my first iteration of the 3D printed portion of the test stand, which so far has a print time of <2H even on my slow little printer. Once I have all the necessary pieces in my possession and I have finished modelling I will post pictures here to get some feedback.

**Comment by hannobraun** [comment]
I've updated this PR with my current state. There are some problems right now:
- The step measurement is finicky. The normal step test (no microstepping) worked when I submitted this, but I've found that I can get it to consistently over- and under-count, depending on the initial position of the magnet.
- I also suspect that the code that handles the rotary encoder count is too simplistic. It should just count in one direction (the expected one), otherwise it might mask errors.
- The `SetStepMode` test works in principle (subject to the problems I just mentioned), but at many microsteps, it generates steps way too slowly. I haven't figured out why yet. Maybe there's something wrong with the timer code, or maybe the compiler just doesn't properly optimize (I've heard that this can happen, if you don't liberally apply `#[inline(always)]`).

I'll keep looking into it.

**Comment by hannobraun** [comment]
Updated. I've improved the reliability of the standard test case, but I think there's still something wrong. I'll look into it some more next week.

**Comment by hannobraun** [comment]
Okay, I'm done here. Two open issues:

- The test works quite reliably, but sometimes it fails because the encoder is missing a count. Maybe that could be fixed in the test code somehow, or it could be a hardware problem (like the vibration from the motor moving the encoder). I'd like to see if the problem persists with future iterations of the test stand.
- I've tabled testing `SetStepMode`. I've spent enough time on the test stand for now and would like to move no to other things. I'll open a draft PR with my in-progress code and an issue to track it, once this PR is merged.

**Comment by hannobraun** [comment]
Issues to open after this is merged:

- [ ] Test `SetStepMode`
- [ ] Add test suite for DRV8825

**Review by jessebraham — APPROVED** [review]
This looks great to me, thanks for doing this!

**Comment by jessebraham** [comment]
I will also take care of the DRV8825 test suite when I get a chance.

**Pull request merged**
